name: Fazer lição

on:
  workflow_dispatch:
    inputs:
      lessons:
        default: 1
        description: 'Números de lições a serem feitas'
        required: true
        type: number

jobs:
  study:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: node index.js
        env:
          DUOLINGO_JWT: ${{ secrets.DUOLINGO_JWT }}
          LESSONS: ${{ inputs.lessons }}
